flysystem:
  storages:
    default.storage:
      adapter: 'aws'
      # visibility: public # Make the uploaded file publicly accessible in S3
      options:
        client: aws.s3 # The service ID of the Aws\S3\S3Client instance
        bucket: 'integr'
        prefix: '/'
        streamReads: true