framework:
  messenger:
    default_bus: command.bus
    buses:
      command.bus:
        middleware:
          - validation
      query.bus:
        middleware:
          - validation
      event.bus:
        default_middleware: allow_no_handlers

    transports:
      # https://symfony.com/doc/current/messenger.html#transport-configuration
      async:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        retry_strategy:
          max_retries: 6
      # failed: 'doctrine://default?queue_name=failed'
      sync: 'sync://'

    routing:
      # Route your messages to the transports
      'Shared\Domain\Command\CommandInterface': sync
      'Shared\Domain\Query\QueryInterface': sync
      'Shared\Domain\Event\EventInterface': async
