security:
  providers:
    app_user_provider:
      entity:
        class: Pim\Domain\Entity\User
        property: token

  firewalls:
    main:
      lazy: true
      provider: app_user_provider
      custom_authenticators:
        - App\Security\UserAuthenticator

  access_control:
    - { path: ^/api/v2/login, roles: PUBLIC_ACCESS }
    - { path: ^/api/v2/file/*, roles: PUBLIC_ACCESS }
    - { path: ^/api/v1/mobzio/excel/*, roles: PUBLIC_ACCESS }
    - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }

  role_hierarchy:
    ROLE_ADMIN: [
      ROLE_PIM_SHOW, ROLE_PIM_EDIT,
      ROLE_OZON,
      ROLE_WILDBERRIES,
      ROLE_INFLUENCE_SHOW, ROLE_INFLUENCE_EDIT,
      ROLE_MOBZIO
    ]
    ROLE_USER: [ ROLE_PIM_SHOW, ROLE_PIM_EDIT ]
    ROLE_PIM_SHOW: [
      ROLE_UNIT_SHOW, ROLE_BRAND_SHOW,
      ROLE_UNIT_SHOW, ROLE_USER_SHOW,
      ROLE_SOURCE_SHOW, ROLE_PRODUCT_SHOW
    ]
    ROLE_PIM_EDIT: [
      ROLE_UNIT_EDIT, ROLE_BRAND_EDIT,
      ROLE_UNIT_EDIT, ROLE_USER_EDIT,
      ROLE_PRODUCT_EDIT
    ]
    ROLE_INFLUENCE_SHOW: [
      ROLE_INFLUENCE_TABLES_SHOW, ROLE_INFLUENCE_FIELDS_SHOW, ROLE_INFLUENCE_VALUES_SHOW
    ]
    ROLE_INFLUENCE_EDIT: [
      ROLE_INFLUENCE_SHOW, ROLE_INFLUENCE_TABLES_EDIT, ROLE_INFLUENCE_FIELDS_EDIT, ROLE_INFLUENCE_VALUES_EDIT
    ]
    ROLE_OZON: [
      ROLE_OZON_PRICE_SHOW, ROLE_OZON_PRICE_EDIT
    ]
    ROLE_WILDBERRIES: [
      ROLE_WB_PRICE_SHOW, ROLE_WB_PRICE_EDIT
    ]

    ROLE_MOBZIO: [
      ROLE_MOBZIO_SHOW, ROLE_MOBZIO_EDIT
    ]