version: '3.7'

services:
  php:
    container_name: integraaal-prod-php
    build:
      context: "./"
      target: php_prod
    depends_on:
      - redis
    ports:
      - "8055:80"
      - "9055:9000"
    networks:
      integraaal-prod:

  redis:
    container_name: integraaal-prod-redis
    image: redis:7-alpine
    networks:
      integraaal-prod:

networks:
  integraaal-prod: