version: '3.7'

services:
  php:
    container_name: integraaal-dev-php
    build:
      context: "./"
      target: php_dev
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - mssql-db
      - redis
    volumes:
      - ./:/usr/app
    working_dir: /usr/app
    ports:
      - "80:80"
      - "8080:8080"
    tty: true

  redis:
    container_name: integraaal-dev-redis
    image: redis:7-alpine
    ports:
      - '6379:6379'

  mssql-db:
    container_name: integraaal-dev-mssql
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: "is765DKJfy*Xd5"
      MSSQL_PID: "Developer"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql:/var/opt/mssql

volumes:
  mssql:
