### Create nomenclatures
POST {{host}}/api/pim/v1/nomenclatures
Content-Type: application/json
X-AUTH-TOKEN: {{token}}

[
  {
    "name": "Омолаживающий крем для лица и век SYN - AKE Peptide, 50 мл",
    "brand": "TO MY SKIN",
    "productLine": null,
    "unit": 1,
    "set": false,
    "status": "В работе"
  }
]