services:
  _defaults:
    autowire: true
    autoconfigure: true

  telegram_handler_main_prod:
    class: Monolog\Handler\TelegramBotHandler
    arguments:
      - '5879871971:AAGXx5wN3nlYi26ycpSHW1vHccoUABEpGh8'
      - '-4052305211'
      - 'error'
  telegram_handler_php_prod:
    class: Monolog\Handler\TelegramBotHandler
    arguments:
      - '5879871971:AAGXx5wN3nlYi26ycpSHW1vHccoUABEpGh8'
      - '-4068197016'
      - 'error'
  telegram_handler_app_prod:
    class: Monolog\Handler\TelegramBotHandler
    arguments:
      - '5879871971:AAGXx5wN3nlYi26ycpSHW1vHccoUABEpGh8'
      - '-4061803950'
  telegram_handler_main_stage:
    class: Monolog\Handler\TelegramBotHandler
    arguments:
      - '5879871971:AAGXx5wN3nlYi26ycpSHW1vHccoUABEpGh8'
      - '-4037016477'
      - 'warning'
  telegram_handler_php_stage:
    class: Monolog\Handler\TelegramBotHandler
    arguments:
      - '5879871971:AAGXx5wN3nlYi26ycpSHW1vHccoUABEpGh8'
      - '-4073777665'
      - 'warning'
  telegram_handler_app_stage:
    class: Monolog\Handler\TelegramBotHandler
    arguments:
      - '5879871971:AAGXx5wN3nlYi26ycpSHW1vHccoUABEpGh8'
      - '-4002630214'

  Shared\:
    resource: '../module/shared/src/'

  Pim\:
    resource: '../module/pim/src/'
    exclude:
      - '../module/pim/src/Domain/Entity'

  Ozon\:
    resource: '../module/ozon/src/'
    exclude:
      - '../module/ozon/src/Domain/Entity'

  Wildberries\:
    resource: '../module/wildberries/src/'
    exclude:
      - '../module/wildberries/src/Domain/Entity'

  Influence\:
    resource: '../module/influence/src/'

  Mobzio\:
    resource: '../module/mobzio/src/'

#  OneC\:
#    resource: '../module/one-c/src/'

  Files\:
    resource: '../module/files/src/'

  App\:
    resource: '../src/'
    exclude:
      - '../src/Kernel.php'

  Shared\Infrastructure\EventBus\EventBus:
    arguments:
      - '@event.bus'

  _instanceof:
    Shared\Domain\Command\CommandHandlerInterface:
      tags:
        - { name: messenger.message_handler, bus: command.bus }

    Shared\Domain\Query\QueryHandlerInterface:
      tags:
        - { name: messenger.message_handler, bus: query.bus }

    Shared\Domain\Event\EventHandlerInterface:
      tags:
        - { name: messenger.message_handler, bus: event.bus }

  Psr\Http\Client\ClientInterface:
    class: GuzzleHttp\Client

aws:
  version: latest
  region: 'ru-msk'
  endpoint: 'https://hb.vkcs.cloud'
  credentials:
    key: 'irSxMmrneMsmqk7jgfFd9u'
    secret: '8RCumWBcXEjb9xEuYsdQ5dZw2kQj84wnF1qahVHc5uH7'

parameters:
  wildberries:
    catalogs: {
      '49': 'Красота'
    }
    union.max: 30
    color.max: 5

    # count of tags and skus - not documented value - may be not relevant
    tag.max: 5
    sku.max: 3

    image: {
      max: 30,
      allow: [ 'png', 'jpg' ]
    }
    video: {
      max: 1,
      allow: [ 'mov', 'mp4' ]
    }

    # TODO: change to prefix
    table.prefix: 'wb_'
    tables: {
      'catalog': 'wb_catalog',
      'attribute': 'wb_attribute',
      'suggest': 'wb_suggest',
      'product': 'wb_product',
      'product-attribute': 'wb_product_attribute',
      'price': 'wb_price',
      'attribute-map': 'wb_attribute_map'
    }
