framework:
  cache:
    default_redis_provider: redis://redis

    app: cache.adapter.redis
    system: cache.adapter.redis

    pools:
      doctrine.result_cache_pool:
        adapter: cache.app
      doctrine.system_cache_pool:
        adapter: cache.system